### ISSUE TITLE
ParentFingerPrint argument is not a buffer

### ISSUE THREAD

**Issue by ArmaghanRaza** [byteball/ocore#159]
finished headless conf
merged app root conf from /home/wilknot/headless-obyte/conf.js
app dir /home/wilknot/headless-obyte
merged user conf from /home/wilknot/.config/headless-obyte/conf.json
app dir /home/wilknot/headless-obyte
path=/home/wilknot/.config/headless-obyte/
createDatabaseIfNecessary byteball.sqlite
takeConnectionFromPool will wait for ready
will archive if exists from unit N6QadI9yg3zLxPMphfNGJcPfddW4yHPkoGMbbGZsWa0=
takeConnectionFromPool will wait for ready
takeConnectionFromPool will wait for ready
stat null
db is now ready
opening new db connection
db is now ready
db is now ready
opened db
db version 22, software version 22
-----------------------
remote access allowed from devices: DEVICE ALLOWED TO CHAT
payouts allowed to address: WHERE THE MONEY CAN BE SENT TO
-----------------------
Passphrase: moqueued jobs: [], locked keys: []
starting network
initCaches
lock acquired [ 'dependencies' ]
setDevicePrivateKey
same device addresses: 0BCK5JVCY3G6ONL3ITWLXE445XBK62OYN
objMyTempDeviceKey not set yet, can't log in
assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: parentFingerPrint argument is not a buffer, it's undefined
    at checkBuffer (/home/wilknot/headless-obyte/node_modules/bitcore-lib/lib/hdpublickey.js:339:5)
    at Function.HDPublicKey._validateBufferArguments (/home/wilknot/headless-obyte/node_modules/bitcore-lib/lib/hdpublickey.js:347:3)
    at HDPublicKey._buildFromBuffers (/home/wilknot/headless-obyte/node_modules/bitcore-lib/lib/hdpublickey.js:296:15)
    at HDPublicKey._buildFromObject (/home/wilknot/headless-obyte/node_modules/bitcore-lib/lib/hdpublickey.js:257:15)
    at new HDPublicKey (/home/wilknot/headless-obyte/node_modules/bitcore-lib/lib/hdpublickey.js:59:23)
    at Object.HDPublicKey (/home/wilknot/headless-obyte/node_modules/bitcore-lib/lib/hdpublickey.js:39:12)
    at createWallet (/home/wilknot/headless-obyte/start.js:156:27)
    at /home/wilknot/headless-obyte/start.js:95:7
    at /home/wilknot/headless-obyte/start.js:220:3
    at /home/wilknot/headless-obyte/node_modules/ocore/sqlite_pool.js:240:5

**Comment by drozd16242283** [comment]
How do you reproduce this error ?
Is this the first launch of headless ?

**Comment by tonyofbyteball** [comment]
It is the first time I hear about this error, please make sure your private key file (.config/headless-obyte/keys.json) is not corrupt.
