### ISSUE TITLE
ER_BAD_FIELD_ERROR: Unknown column 'getters' in 'field list'

### ISSUE THREAD

**Issue by Leonix** [byteball/ocore#290]
I'm getting this error trying to sync full node with MySQL storage:
```
stack Error: ER_BAD_FIELD_ERROR: Unknown column 'getters' in 'field list'
    at Query.Sequence._packetToError (D:\progs\Obyte\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\progs\Obyte\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\progs\Obyte\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\progs\Obyte\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\progs\Obyte\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\progs\Obyte\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\progs\Obyte\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\progs\Obyte\node_modules\mysql\lib\Connection.js:526:10)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    --------------------
    at Protocol._enqueue (D:\progs\Obyte\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at PoolConnection.query (D:\progs\Obyte\node_modules\mysql\lib\Connection.js:198:25)
    at PoolConnection.safe_connection.query (D:\progs\Obyte\node_modules\ocore\mysql_pool.js:64:41)
    at D:\progs\Obyte\node_modules\ocore\storage.js:857:10
    at Object.determineGetterProps (D:\progs\Obyte\node_modules\ocore\aa_validation.js:755:10)
    at D:\progs\Obyte\node_modules\ocore\storage.js:856:18
    at D:\progs\Obyte\node_modules\async\dist\async.js:3110:16
    at replenish (D:\progs\Obyte\node_modules\async\dist\async.js:1011:17)
    at D:\progs\Obyte\node_modules\async\dist\async.js:1016:9
    at eachLimit$1 (D:\progs\Obyte\node_modules\async\dist\async.js:3196:24)
```

Looks like table `aa_addresses` is missing column `getters`
https://github.com/byteball/ocore/blob/master/initial-db/byteball-mysql.sql#L795
this column is used in query at ocore/storage.js:857
https://github.com/byteball/ocore/blob/master/storage.js#L857

**Comment by tonyofbyteball** [comment]
Thanks for the bug report. That was fixed in https://github.com/byteball/ocore/commit/2d104a9181ad219b8f31736feda9ebade9b3b8ae. You'll need to add the column manually or start a fresh sync.
